#!/bin/bash

#
# Check if flexget is running, if it is stop it
#

echo -n "Checking if flexget.service is running: "
if [[ $(systemctl --user is-active flexget) != active ]]; then
	echo "flexget.service is not running, proceeding"
else
	echo -n "flexget.service is running, stopping it"
	systemctl --user stop flexget
	echo " - STOPPED"
fi

#
# Check if transmission configuration check daemon is running
#

echo -n "Checking if check-torrent-service.service is running: "
if [[ $(systemctl --user is-active check-torrent-service) != active ]]; then
	echo "check-torrent-service is not running, proceeding"
else
	echo -n "check-torrent-service is running, stopping it"
	systemctl --user stop check-torrent-service
	echo " - STOPPED"
fi

#
# Check if transmission is running, if it is stop it
#

echo -n "Checking if transmission.service is running: "
if [[ $(systemctl is-active transmission) != active ]]; then
	echo "transmission.service is not running, proceeding" 
else
	echo -n "transmission.service is running, stopping it"
	sudo systemctl stop transmission
	echo " - STOPPED"
fi
#
# Check if openvpn is running, if it is stop it
#

echo -n "Checking if openvpn-client@ovpn is running: "
if [[ $(systemctl is-active openvpn-client@ovpn) != active ]]; then
	echo "openvpn is not running, proceeding"
else
	echo -n "openvpn is running, stopping it"
	sudo systemctl stop openvpn-client@ovpn
	echo " - STOPPED"
fi

#
# Check if tun0 exists, if it does remove it
#

echo -n "Checking if tun0 interface exists: "
ip a s dev tun0 >/dev/null 2>&1
if [ $? = 1 ]; then
	echo "tun0 does not exist, proceeding"
else
	echo -n "found tun0, removing it"
	sudo openvpn --rmtun --dev tun0 >/dev/null 2>&1
	echo " - REMOVED"
fi

