#!/bin/bash
#
# This script has a dependency on package colordiff. Either install it or modifiy it to use regular diff.
# See comment below on where to do that.
#

# User defined variables
HOST="$(hostname)"
BACKUPREPO="/hive/backup/$HOST"

# Define some colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

FILENAME="$1"

# Function to show list of files
showFileList () {
	INDEX=1
	for FILEPOINTER in "${FILEPOINTERS[@]}"; do
		echo -e "${GREEN}$INDEX${NC}: $(echo $FILEPOINTER | rev | cut -d '/' -f-2 | rev)"
		let INDEX=INDEX+1
	done
}

# Function to replace original with backup file
replaceFile () {
	printf '\e[A\e[K'
	echo -e "Really replace?"
	echo -e "${RED}---${NC} $(cat $DIFFSOURCE)"
	echo -e "with"
	echo -e "${GREEN}+++${NC} $CHOICE\n"
	echo -en "Answer (y)es, or any other key will abort: "
	
	read ANSWER
	if [ $ANSWER == "y" ]; then
	 	echo -e "\nDEBUG: ${RED}mv $(cat $DIFFSOURCE) "$(cat $DIFFSOURCE)".bak${NC}"
		echo -e "DEBUG: ${RED}cp $CHOICE $(cat $DIFFSOURCE)${NC}"  
		echo -e "\n${RED}$(cat $DIFFSOURCE)${NC} replaced with ${GREEN}$CHOICE${NC}"
		echo -e "A backup of original has been saved to "${GREEN}$(cat $DIFFSOURCE)".bak${NC}"
		exit 0
	else 
		echo -e "Aborting\n"
		continue
	fi
}

# Make answers non case sensitive
shopt -s nocasematch

# Check that we are running as root
if [ "$(whoami)" != "root" ]; then
	echo "You need to run this script with sudo"
	exit 1
fi

if [ -z $@ ]; then
	echo "Usage: restore <filename>"
	exit 1
fi

SEARCHRESULT="$(find $BACKUPREPO -name $FILENAME -printf '%T@ %p\n' | sort -nr | awk '{print $2}')"

if [ -z $(echo $SEARCHRESULT | sed 's/ //g') ]; then
	echo "Backup of $FILENAME was not found in $BACKUPREPO"
	exit 1
else
	COUNT=0
	while read -r LINE; do
		FILEPOINTERS+=("$LINE")
		FILEPATH="$(dirname $LINE)"
		DIFFSOURCES+=("${FILEPATH}/.$FILENAME.path")
		let COUNT=COUNT+1
	done <<< "$SEARCHRESULT"
fi


while true; do
	clear

	echo -e "\nFound $COUNT backups"
	showFileList
	

	echo -en "\nDiff original with which (n) file?: "
	read FILENUMBER

	if [[ ! "$FILENUMBER" =~ ^[0-9]*$ ]] ; then
		echo "Only valid input is numbers or (q)uit"
		sleep 2
		continue
	elif [ $FILENUMBER -gt $COUNT -o $FILENUMBER -lt 1 ] ; then
		echo "Please input a number between 1 and $COUNT"
		sleep 2
	else
		let FILENUMBER=FILENUMBER-1
		CHOICE="${FILEPOINTERS[$FILENUMBER]}"
		DIFFSOURCE="${DIFFSOURCES[$FILENUMBER]}"
		echo ""
	 	colordiff -Naur $(cat $DIFFSOURCE) $CHOICE 

		# If there is no difference between files, return to menu. 
		if [ $? = "0" ]; then
			echo -n "No difference between files"
			sleep 2
		else
			echo -en "\n(R)eplace? (Any other key will return to list of backups): "
			read ACTION

			case "$ACTION" in
				r) replaceFile
				;;
				
				*) echo ""
				;;
			esac

		fi
	fi 

done
