#!/bin/bash

FILENAME="$1"
HOST="bishop"
FILELIST="/home/$USER/.config/filelist"
BACKUPREPO="/hive/backup/$HOST"

showFileList () {
	INDEX=1
	for i in "${FILEPOINTERS[@]}"; do
		echo "$INDEX: $i"
		let INDEX=INDEX+1
	done
}

if [ "$(whoami)" != "root" ]; then
	echo "You need to run this script with sudo"
	exit 1
fi

if [ -z $@ ]; then
	echo "Usage: restore <filename>"
	exit 1
fi

SEARCHRESULT="$(find $BACKUPREPO -name $FILENAME -printf '%T@ %p\n' | sort -nr | awk '{print $2}')"

if [ -z $(echo $SEARCHRESULT | sed 's/ //g') ]; then
	echo "Backup of $FILENAME was not found in $BACKUPREPO"
	exit 1
else
	COUNT=0
	while read -r LINE; do
		FILEPOINTERS+=("$LINE")
		FILEPATH="$(dirname $LINE)"
		DIFFSOURCES+=("${FILEPATH}/.$FILENAME.path")
		let COUNT=COUNT+1
	done <<< "$SEARCHRESULT"
fi


while true; do

	echo ""
	echo "Found $COUNT backups"
	showFileList
	
	echo ""
	echo -n "Diff original with which (N) file?: "
	read FILENUMBER

	if [ "$FILENUMBER" -gt "$COUNT" -o "$FILENUMBER" -lt "1" ]; then
		echo "Choice is out of range"
	else
		let FILENUMBER=FILENUMBER-1
		CHOICE="${FILEPOINTERS[$FILENUMBER]}"
		DIFFSOURCE="${DIFFSOURCES[$FILENUMBER]}"
		echo ""
	 	colordiff -Naur $CHOICE $(cat $DIFFSOURCE)

		if [ $? = 0 ]; then
			echo "No difference between files"
			else
			echo ""
			echo -n "(R)eplace original with backup?: "
			read ACTION
			shopt -s nocasematch

			case "$ACTION" in
				r) echo Replace
				;;

				*) echo Something else? 
				;;
			esac

		fi
	fi 

done
