#!/bin/bash
eth=enp5s4
local_ip=$(ip addr show $eth | grep "inet\b" | awk '{print $2}')
default_gateway=$(ip r s | grep default | awk '{print $3}')
vpn_ip=$(ip addr show tun0 | grep "inet\b" | awk '{print $2}')
vpn_gateway=$(ip route show table 10 | awk '{print $3}')
external_ip=$(wget --bind-address=$(echo $local_ip | cut -d/ -f1) http://ipecho.net/plain -O - -q)
external_vpn_ip=$(wget --bind-address=$(echo $vpn_ip | cut -d/ -f1) http://ipecho.net/plain -O - -q)
transmission_config="/home/splump/.config/transmission-daemon/settings.json"

echo ""
echo "Local IP adress is: $local_ip"
echo "Default Gateway is: $default_gateway"
echo "VPN IP adress is: $vpn_ip"
echo "VPN Gateway is: $vpn_gateway"
echo "External IP is: $external_ip"
echo "External VPN IP is: $external_vpn_ip"
echo ""
echo -n "Transmission has been reconfigured as follows:" 
grep ipv4 $transmission_config
echo ""
