#!/bin/bash

# SETUP #
SERVERIP=10.0.0.3
SERVERPORT=8080
SERVERMAC=c8:bc:c8:a3:36:b8

WAKELAN=/usr/bin/wol
CURL=/usr/bin/curl

#$WAKELAN $SERVERMAC
#sleep 10
echo "Sending command to update Kodi music library"
$CURL --data-binary '{ "jsonrpc": "2.0", "id": "mybash", "method": "AudioLibrary.Scan"}' -H 'content-type: application/json;' http://kodi:k4k0d1rv@$SERVERIP:$SERVERPORT/jsonrpc &> /dev/null
echo "Sending command to update Subsonic media folders"
curl -s 'http://admin:tKk4ZiLHrf46c3vrwFs8kwWd@127.0.0.1:4040/subsonic/musicFolderSettings.view?scanNow&v=1.12.0&c=myapp' >/dev/null
exit 0
