directory: /hive/music
library: /hive/music/.library.blb

plugins: fetchart lastgenre info discogs bandcamp inline

ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

import:
  copy: yes
  write: yes
  resume: ask
  quiet_fallback: skip
  log: beetslog.txt

match:
  required: year

paths:
  default: $albumartist/$album ($year)/%if{$multidisc,$disc.}$track. $title
  comp: Various Artists/$album ($year)/%if{$multidisc,$disc.}$track. $title
item_fields:
  multidisc: 1 if disctotal > 1 else 0

bandcamp:
  art: true

fetchart:
  cautious: true
  cover_names: front
  sources: bandcamp itunes *

ignore: .AppleDouble ._* *~ .DS_Store
art_filename: cover
threaded: yes
